//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenaWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camps38
    {
        public string old_site_code { get; set; }
        public string company { get; set; }
        public Nullable<double> HajNo { get; set; }
        public Nullable<double> area { get; set; }
        public string street { get; set; }
        public string gate { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string shakes { get; set; }
        public Nullable<int> site_code { get; set; }
        public Nullable<int> getin { get; set; }
        public Nullable<int> getout { get; set; }
        public string BOX_ID { get; set; }
        public int ID { get; set; }
    
        public virtual sites sites { get; set; }
    }
}
