//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenaWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sites
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sites()
        {
            this.camps38 = new HashSet<camps38>();
        }
    
        public int site_code { get; set; }
        public string old_site_code { get; set; }
        public string stage { get; set; }
        public string contractor { get; set; }
        public string section { get; set; }
        public Nullable<int> metawef { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> ac_type { get; set; }
        public Nullable<int> old_qty { get; set; }
        public Nullable<int> new_qty { get; set; }
        public Nullable<int> contractor_ID_old { get; set; }
        public Nullable<int> contractor_ID_new { get; set; }
        public Nullable<int> week_ID_new { get; set; }
        public Nullable<int> week_ID_Old { get; set; }
        public Nullable<int> old_status { get; set; }
        public Nullable<int> new_status { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> latitude2 { get; set; }
        public Nullable<double> Longitude2 { get; set; }
        public Nullable<double> latitude1 { get; set; }
        public Nullable<double> Longitude1 { get; set; }
        public Nullable<double> latitude3 { get; set; }
        public Nullable<double> Longitude3 { get; set; }
        public Nullable<double> latitude4 { get; set; }
        public Nullable<double> Longitude4 { get; set; }
        public Nullable<int> month_new { get; set; }
        public Nullable<int> month_old { get; set; }
        public Nullable<int> install_month { get; set; }
        public Nullable<int> install_stage { get; set; }
        public Nullable<int> installQty { get; set; }
        public Nullable<int> old_3_4 { get; set; }
        public Nullable<int> old_3_2 { get; set; }
        public Nullable<int> sub_contractor { get; set; }
        public Nullable<int> gaz { get; set; }
        public string bcolor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<camps38> camps38 { get; set; }
    }
}
